### ISSUE TITLE
Error updating stats

### ISSUE THREAD

**Issue by ylong8** [lbrictson/pypubg#12]
Hi,

I got errors when trying to get stats. For example:

>>> api.player("yyf123")
{'error': 1, 'message': 'Error updating stats. Please try again later.'}

Also, another error shows that:

>>> api.player_mode_stats("yyf123", game_mode='solo', game_region='as')
Unhandled exception: 'Stats'
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    api.player_mode_stats("yyf123", game_mode='solo', game_region='as')
  File "C:\Users\longx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pypubg\core.py", line 59, in player_mode_stats
    for stat in data['Stats']:
KeyError: 'Stats'

Is there something wrong with my api key?

Thank you!

**Comment by canonkissx4** [comment]
@ylong8 Hi, The same problem happened from recently.
It seems occurred "PUBG Tracker Battlegrounds API(TRN)" site - API disabled.

I have confirmed this message without pypubg library.

```
{
     "error": "Api is temporarily disabled for maintenance or server issues. Sorry!"
 }
```

Should I wait for them to fix the API issue

Thanks.

**Comment by ghost** [comment]
> The API is currently disabled.

https://pubgtracker.com/site-api

**Comment by benjamincampbell** [comment]
Is it possible for us to get some sort of ETA for the API to be re-enabled? As of 10/18 it's still disabled.

I understand PUBG Tracker is a huge project, I was just excited to find this and implement it and was wondering how long I may have to wait to do so.

**Comment by ghost** [comment]
I already have API-KEY but too unstable recently (almost 3~4 weeks). I can't do anything but I pray that PUBG Tracker API re-enabled.

**Comment by zt2191stat** [comment]
Still got this problem after they re-enabled the api.

> {'error': 1, 'message': 'Error updating stats. Please try again later.'}
