### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by XedGo** [lbrictson/pypubg#18]
i got it
_________________________________________________________________________

`/usr/bin/python2.7 /home/mon/桌面/python/untitled1/untitled1.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Unhandled exception: No JSON object could be decoded
[2017-11-13 10:09:00,997] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/mon/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mon/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mon/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mon/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mon/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mon/桌面/python/untitled1/untitled1.py", line 10, in hello_world
    api.player_mode_stats("akustic", game_mode="squad")
  File "/usr/local/lib/python2.7/dist-packages/pypubg/core.py", line 57, in player_mode_stats
    data = json.loads(response.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by alex943** [comment]
It is generally considered that "503“ response or other similar status will invoke this error.
