### ISSUE TITLE
Error expecting value

### ISSUE THREAD

**Issue by Benjamin-Connelly** [lbrictson/pypubg#5]
>>> api.player_mode_stats("akustic", game_mode="squad")
Unhandled exception: Expecting value: line 3 column 1 (char 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pypubg/core.py", line 45, in player_mode_stats
    data = json.loads(response.text)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)
>>> api.player_skill("akustic", game_mode="solo")
Unhandled exception: Expecting value: line 3 column 1 (char 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pypubg/core.py", line 62, in player_skill
    data = json.loads(response.text)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

**Comment by lbrictson** [comment]
@bc-drop  it looks like the PUBG tracker site this library interfaces with is returning errors at the moment, so that is the issue.  Potentially it is down?

I'll shoot them an email and see what I can find out.  From your code you have everything right though!

**Comment by Benjamin-Connelly** [comment]
Thank you!


On July 17, 2017 at 9:48:34 PM, lbrictson (notifications@github.com) wrote:

@bc-drop <https://github.com/bc-drop> it looks like the PUBG tracker site
this library interfaces with is returning errors at the moment, so that is
the issue. Potentially it is down?

I'll shoot them an email and see what I can find out. From your code you
have everything right though!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lbrictson/pypubg/issues/5#issuecomment-315942873>, or mute
the thread

**Comment by lbrictson** [comment]
@bc-drop  Looks like their site is functional again, you should be all set.

Let me know if it works/doesn't
